export const TEAM_MEMBERS_LIST_REQUEST = 'TEAM_MEMBERS_LIST_REQUEST'
export const TEAM_MEMBERS_LIST_SUCCESS = 'TEAM_MEMBERS_LIST_SUCCESS'
export const TEAM_MEMBERS_LIST_FAILURE = 'TEAM_MEMBERS_LIST_FAILURE'
export const TEAM_MEMBERS_LIST_FILTER_CLEAR = 'TEAM_MEMBERS_LIST_FILTER_CLEAR'

export const SEARCH_PROJECTS_LIST_SUCCESS = 'SEARCH_PROJECT_LIST_SUCCESS'
export const SEARCH_PROJECTS_LIST_FAILURE = 'SEARCH_PROJECT_LIST_FAILURE'
export const SEARCH_PROJECTS_LIST_CLEAR = 'SEARCH_PROJECT_LIST_CLEAR'

export const SEARCH_SKILLS_LIST_SUCCESS = 'SEARCH_SKILLS_LIST_SUCCESS'
export const SEARCH_SKILLS_LIST_FAILURE = 'SEARCH_SKILLS_LIST_FAILURE'
export const SEARCH_SKILLS_LIST_CLEAR = 'SEARCH_SKILLS_LIST_CLEAR'

export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'
