export const TEAM_MEMBERS_LIST_REQUEST = 'TEAM_MEMBERS_LIST_REQUEST'
export const TEAM_MEMBERS_LIST_SUCCESS = 'TEAM_MEMBERS_LIST_SUCCESS'
export const TEAM_MEMBERS_LIST_FAILURE = 'TEAM_MEMBERS_LIST_FAILURE'

export const RESET_NOTIFICATION = 'RESET_NOTIFICATION'
